Update gateapi based on gate 1.22 tag
spinnaker/spin pull request #319
Opened 2021-05-20 13:53 UTC by mbwhelan

* Update gateapi based on https://github.com/spinnaker/gate/releases/tag/version-1.22.0
* Upgraded to Go 1.16
* Upgraded  `k8s.io/client-go v0.21.1`

2021-06-03 00:56 UTC, kskewes commented
Would be great to progress this. `trivy` container scanner is failing current tagged release 1.22.0 due to a HIGH CVE in crypto library.

```
+---------------------+------------------+----------+------------------------------------+------------------------------------+---------------------------------------+
|       LIBRARY       | VULNERABILITY ID | SEVERITY |         INSTALLED VERSION          |           FIXED VERSION            |                 TITLE                 |
+---------------------+------------------+----------+------------------------------------+------------------------------------+---------------------------------------+
| golang.org/x/crypto | CVE-2020-29652   | HIGH     | v0.0.0-20191011191535-87dc89f01550 | v0.0.0-20201216223049-8b5274cf687f | golang: crypto/ssh: crafted           |
|                     |                  |          |                                    |                                    | authentication request can            |
|                     |                  |          |                                    |                                    | lead to nil pointer dereference       |
|                     |                  |          |                                    |                                    | -->avd.aquasec.com/nvd/cve-2020-29652 |
+                     +------------------+          +                                    +------------------------------------+---------------------------------------+
|                     | CVE-2020-9283    |          |                                    | v0.0.0-20200220183623-bac4c82f6975 | golang.org/x/crypto: Processing       |
|                     |                  |          |                                    |                                    | of crafted ssh-ed25519                |
|                     |                  |          |                                    |                                    | public keys allows for panic          |
|                     |                  |          |                                    |                                    | -->avd.aquasec.com/nvd/cve-2020-9283  |
+---------------------+------------------+----------+------------------------------------+------------------------------------+---------------------------------------+
```

2022-03-12 19:46 UTC, kskewes approved these changes

2022-03-12 19:52 UTC, kskewes requested changes
We're getting ready to cut 1.27.0 and it would be great to merge this in.

@mbwhelan - would you have time to rebase this on master to pull in the mergify change  https://github.com/spinnaker/spin/pull/327 ?

Then I think we can backport/cherry-pick to `release-1.27.x` branch.

2022-04-05 03:50 UTC, kskewes-sf commented
Thanks and apologies we didn't get there with this PR. It has been superseded now and can be closed.

2022-04-28 02:22 UTC, closed without merging