refactor(auth): improve authentication flow for oauth 2.0 with local webserver
spinnaker/spin pull request #325
Opened 2022-02-17 02:58 UTC by GennadySpb

2022-04-20 12:48 UTC, GennadySpb commented
Hey @dbyron-sf ! Could your check out PR?

2022-04-20 15:05 UTC, dbyron-sf commented
> Hey @dbyron-sf ! Could your check out PR?

I suspect @kskewes-sf is in a better position to review this.

2022-04-21 22:58 UTC, kskewes-sf commented
Sure, I remember the interactive cli driven flow and this looks interesting.
I need to refresh myself on spin's oauth flow and get a local setup going which I want to do after we get release 1.27.0 out. Sound okay @GennadySpb ?
There are several reports of `spin` CLI being broken since 1.14 so it would be good to validate before introducing new changes.
That said will do a quick pass through PR.

2022-04-21 23:14 UTC, kskewes-sf requested changes

2022-04-21 23:14 UTC, kskewes-sf commented on cmd/gateclient/oauth.go
> +		// TODO: add handle of `error`
This is commented but new in this PR. Can you give an example of what `error` is here?
Could be something for a follow up PR.

2022-04-21 23:14 UTC, kskewes-sf commented on cmd/gateclient/oauth.go
> +func startWebServer() (codeCh chan string, err error) {
Can you add a test for this please? - see: https://pkg.go.dev/net/http/httptest
We can validate:
1. `code` FormValue is supplied in test and plumbed through to codeCh
2. http response recorder has correct output
3. listener closed
4. `error` FormValue (per next comment - if part of this PR).

2022-04-21 23:35 UTC, kskewes-sf commented on cmd/gateclient/oauth.go
> +func openURL(url string) error {
Using a local web server or prompt is optional in the linked code and this seems quite robust. If local web server doesn't work then use the prompt. https://github.com/youtube/api-samples/blob/master/go/oauth2.go

I'm not sure what the failure modes are for the various `openURL()` commands, like `exec` hanging with no feedback. I've managed to misconfigure Linux for `xdg-open` more than once :sweat_smile: 

If an error is returned we bail out at L48 with `log.Fatalf` and there is no way for a user to progress unless they fix the exec issue.

I wonder if we might want to do something like:
a) fall back to prompt for code?
b) make `localWebServer` selectable via spin config (default enabled?) similer to https://github.com/youtube/api-samples/blob/07263305b59a7c3275bc7e925f9ce6cabf774022/go/oauth2.go#L44 

WDYT?

2025-10-02 03:41 UTC, closed without merging