Add arm64 binary build for M1 chip
spinnaker/spin pull request #334
Opened 2022-03-30 16:11 UTC by roee-landesman

The intention of this PR is to add an `arm64` build of spin CLI so that it can be downloaded natively on M1 macbooks. This was discussed on this thread: https://github.com/spinnaker/spinnaker/issues/6632#issuecomment-1082726391

2022-03-30 23:05 UTC, kskewes-sf requested changes

2022-03-30 23:05 UTC, kskewes-sf commented on .github/workflows/build.yml
> +          GOARCH=arm64 GOOS=windows go build -ldflags "${LDFLAGS}" -o dist/${{ steps.release_info.outputs.RELEASE_VERSION }}/darwin/arm64/spin.exe .
```suggestion
          GOARCH=arm64 GOOS=darwin go build -ldflags "${LDFLAGS}" -o dist/${{ github.ref_name }}/${{ steps.build_variables.outputs.VERSION_WITHOUT_BRANCH }}/darwin/arm64/spin .
```

We need to target `darwin` OS.
Unfortunately the lines are slightly different between the 3 different files.

2022-03-30 23:05 UTC, kskewes-sf commented on .github/workflows/pr.yml
> +          GOARCH=arm64 GOOS=windows go build -ldflags "${LDFLAGS}" -o dist/${{ steps.release_info.outputs.RELEASE_VERSION }}/darwin/arm64/spin.exe .
```suggestion
          GOARCH=arm64 GOOS=darwin go build -ldflags "${LDFLAGS}" -o dist/${{ steps.build_variables.outputs.VERSION }}/darwin/arm64/spin .
```

2022-03-30 23:05 UTC, kskewes-sf commented on .github/workflows/release.yml
> +          GOARCH=arm64 GOOS=windows go build -ldflags "${LDFLAGS}" -o dist/${{ steps.release_info.outputs.RELEASE_VERSION }}/darwin/arm64/spin.exe .
```suggestion
          GOARCH=arm64 GOOS=darwin go build -ldflags "${LDFLAGS}" -o dist/${{ steps.release_info.outputs.RELEASE_VERSION }}/darwin/arm64/spin .
```

2022-03-31 01:28 UTC, kskewes-sf approved these changes
np. LGTM. We'll need a maintainer to review/approve and let CI run for us.

2022-04-01 12:58 UTC, mattgogerly commented
Hi! Looks like the build is failing, any chance you could take a look? @kskewes-sf @roee-landesman

2022-04-01 17:20 UTC, roee-landesman commented
Unfortunately I believe this may be because we are running go `1.15` precompiled from upstream. See: https://github.com/golang/go/issues/44703#issuecomment-788537428. Is there an effort to upgrade the spin CLI to newer versions of Go?

2022-04-03 21:12 UTC, kskewes-sf commented
Good find. Yes let's upgrade. 
Maybe to 1.17 as 1.18 is new so might not be widely used or available by users of `spin` and there's also no patch version yet.
```
$ GOARCH=arm64 GOOS=darwin go1.15.15 build .
# github.com/spinnaker/spin
/home/kskewes/sdk/go1.15.15/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/tmp/go-link-542414637/go.o: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status
```

```
$ GOARCH=arm64 GOOS=darwin go1.16.15 build .
$ file spin
spin: Mach-O 64-bit arm64 executable, flags:<|DYLDLINK|PIE>
```

2022-04-03 21:27 UTC, kskewes-sf commented
See #335 - once merged that will unblock this PR.

2022-04-04 07:24 UTC, mattgogerly commented
@Mergifyio update

2022-04-04 07:29 UTC, mattgogerly approved these changes

2022-04-04 07:30 UTC, merged

2022-04-04 19:14 UTC, kskewes-sf commented
Can see binary here: https://console.cloud.google.com/storage/browser/spinnaker-artifacts/spin/master/f227e58-202204040731/darwin/arm64